server:
  port: 8001

spring:
  application:
    name: micro-zhifubao
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 #采用比例，默认0.1，全部采样1.0
  zipkin:
    base-url: http://149.129.67.83:9411/ #指定zipkin的服务器地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#暴露hystrix stream端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream