server:
  port: 7500

spring:
  application:
    name: micro-config
  rabbitmq:
    host: 149.129.67.83
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/PgUpPgD/spboot1.git
          # Git\u4ED3\u5E93\u5982\u679C\u662F\u79C1\u6709\u4ED3\u5E93\u9700\u8981\u586B\u5199\u7528\u6237\u540D\u5BC6\u7801\uFF0C\u793A\u4F8B\u662F\u516C\u5F00\u4ED3\u5E93\uFF0C\u6240\u4EE5\u4E0D\u914D\u7F6E\u5BC6\u7801\u3002
#          username:
#          password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#暴露端点 配置中心担任调用/bus-refresh的任务
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh